services:
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    environment:
      - 'ACCEPT_EULA=yes'
      - 'MSSQL_PID=express'
      - 'MSSQL_SA_PASSWORD=verYs3cret'
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'verYs3cret' -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
